### ISSUE TITLE
Initial MVP

### ISSUE THREAD

**Issue by bryceschober** [cpputest/conan-cpputest#1]
This conan.io recipe is based on the one from @matlo607 from cpputest/cpputest#1115, but has some critical fixes and differences:
1. I set it up to build latest master, since 3.8 is so old
1. I used the https://github.com/conan-io/conan-package-tools for boot-strapping public open-source continuous integration
1. It exports the conan build flags to CppUTest, as was necessary for 32-bit builds
1. It includes a basic package test

Things I haven't yet done include:
- [x] Migrate this project to the cpputest organization at cpputest/conan-cpputest.
- [ ] Think about the best way to provide 3.8 vs. master vs. some-other-kind-of-reasonably-stable builds
    - [ ] #8 Records some ideas to try for this
- [x] hook up GitLab as a CI mirror at https://gitlab.com/bryceschober/conan-cpputest
- [x] Hooking up accounts to Travis for OSX and AppVeyor for Windows builds:
    - [ ] #4 OSX build fails on Travis (I need help!)
    - [ ] #5 Windows build fails on AppVeyor (I need help!)
- [x] Hooking up to a bintray account to upload and store packages:
    https://bintray.com/bryceschober/bks-conan/CppUTest:bryceschober
- [x] Expose most / all CppUTest configurations as conan options
  - [x] Merged #6 with most CppUTest options
- [ ] Add actual user docs to the README.md
- [x] Add CI status badges to the README.md
- [ ] Submit to conan-center

**Comment by bryceschober** [comment]
GitLab is currently a pull mirror for GitHub, so PRs need to be on GitHub. If you don't think that GitHub really gives us many advantages for exposure / collaborating with CppUTest maintainers, then I'd probably just move everything to GitLab.

To CppUTest maintainers: @basvodde, @jwgrenning
And to Conan.io package interest: @matlo607, @shreyasbharath, @ZaMaZaN4iK, @kkass

Do you have opinions on primary hosting via GitLab vs. GitHub?

**Comment by bryceschober** [comment]
I've now hooked up Travis and Appveyor, but both OSX (#4) and Windows (#5) builds are failing.

I'm probably going to need help to get those working.

**Comment by offa** [comment]
@basvodde has created a repository https://github.com/cpputest/cpputest/issues/1115

What about moving development to there @bryceschober ? 

> Do you have opinions on primary hosting via GitLab vs. GitHub?

Unfortunately whatever is chosen, it is not ideal; GH connects Travis and AppVeyor while GL connects Gitlab CI. At least we should decide, where the main focus is (Issues, PRs etc.).

**Comment by bryceschober** [comment]
Actually, note that PR #6 did actually trigger and report gitlab status, so staying on GitHub sounds like it will be best. I'm hoping to just transfer this project into the cpputest org under @basvodde's control and maintain it from there.
